version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /app/node_modules
      - ./src:/app/src
    depends_on:
      data-source:
        condition: service_healthy
  data-source:
    image: 'postgres:latest'
    container_name: data-source
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'db'
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s
      retries: 5
